name: Mod Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Android NDK
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25c
        local-cache: true

    - name: Build
      run: ndk-build NDK_PROJECT_PATH=./build APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk NDK_DEBUG=0 -j12

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/libs/armeabi-v7a/*.so
        tag_name: v${{ github.run_number }}
        title: Release ${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
